In [1]:
import otter
grader = otter.Notebook()

# Homework 2: Arrays and Tables

In [2]:
# Don't change this cell; just run it.
# When you log-in please hit return (not shift + return) after typing in your email
import numpy as np
from datascience import *


**Recommended Reading**: 
* [Data Types](https://inferentialthinking.com/chapters/04/Data_Types.html) 
* [Sequences](https://inferentialthinking.com/chapters/05/Sequences.html)
* [Tables](https://inferentialthinking.com/chapters/06/Tables.html)

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to load the provided tests. Each time you start your server, you will need to execute this cell again to load the tests.
 
Throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. 

<font color="#E74C3C">**Important**: In this homework, the `ok` tests will tell you whether your answer is correct, except for Parts 4 & 5. In future homework assignments, correctness tests will typically not be provided.</font>

## 1. Creating Arrays


**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the floor of 12.6
3. 3
4. 5 to the power of the ceil of 5.3

*Hint:* `floor` and `ceil` are functions in the `math` module. Importing modules is covered in Lab 2!

*Note:* Python lists are different/behave differently than NumPy arrays. In SBCC's Data Science course, we use NumPy arrays, so please make an **array**, not a Python list.

<!--
BEGIN QUESTION
name: q1_1
-->

In [3]:
# Our solution involved one extra line of code before creating
# weird_numbers.
from math import *
weird_numbers = [-2, floor(12.6), 3, 5**ceil(5.3)]
weird_numbers

[-2, 12, 3, 15625]

In [4]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

<!--
BEGIN QUESTION
name: q1_2
-->

In [5]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'],
      dtype='<U10')

In [6]:
grader.check("q1_2")

q1_2 results: All test cases passed!

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"CS118".join(book_title_words)` .

<!--
BEGIN QUESTION
name: q1_3
-->

In [7]:
with_commas = ', '.join(book_title_words)
without_commas = ' '.join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


In [8]:
grader.check("q1_3")

q1_3 results: All test cases passed!

## 2. Indexing Arrays


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.

*Note:* If you have previous coding experience, you may be familiar with bracket notation. DO NOT use bracket notation when indexing (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting. This can cause you to fail an autograder test.**

Be sure to refer to the [Python Reference](http://data8.org/sp22/python-reference.html) on the website if you feel stuck!

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

<!--
BEGIN QUESTION
name: q2_1
-->

In [9]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers[2]
third_element

-6

In [10]:
grader.check("q2_1")

q2_1 results: All test cases passed!

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table.

*Hint:* Replace the `...` with strings or numbers. As a reminder, indices should be **integers**.

<!--
BEGIN QUESTION
name: q2_2
-->

In [11]:
blank_a = 'third'
blank_b = 'fourth'
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

In [12]:
grader.check("q2_2")

q2_2 results: All test cases passed!

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

<!--
BEGIN QUESTION
name: q2_3
-->

In [13]:
# index_of_last_element = -1
index_of_last_element = 141

In [14]:
grader.check("q2_3")

q2_3 results: All test cases passed!

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  Calling `.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births` table. The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

<!--
BEGIN QUESTION
name: q2_4
-->

In [15]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = president_birth_years[len(president_birth_years)-1]
most_recent_birth_year

1917

In [16]:
grader.check("q2_4")

q2_4 results: All test cases passed!

**Question 5.** Finally, assign `sum_of_birth_years` to the sum of the first, tenth, and last birth year in `president_birth_years`.

<!--
BEGIN QUESTION
name: q2_5
-->

In [17]:
sum_of_birth_years = president_birth_years[0] + president_birth_years[9] + president_birth_years[-1]

In [18]:
grader.check("q2_5")

q2_5 results: All test cases passed!

## 3. Basic Array Arithmetic


**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157. Assign each variable below such that `first_product` is assigned to the result of $42 * 157$, `second_product` is assigned to the result of $4224 * 157$, and so on. 

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
-->

In [19]:
first_product = 42 * 157
second_product = 4224 * 157
third_product = 42422424 * 157
fourth_product = -250 * 157
print(first_product, second_product, third_product, fourth_product)

6594 663168 6660320568 -39250


In [20]:
grader.check("q3_1")

q3_1 results: All test cases passed!

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

<!--
BEGIN QUESTION
name: q3_2
-->

In [21]:
numbers = [42, 4224, 42422424, -250]
products = [number * 157 for number in numbers]
products

[6594, 663168, 6660320568, -39250]

In [22]:
grader.check("q3_2")

q3_2 results: All test cases passed!

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

<!--
BEGIN QUESTION
name: q3_3
-->

In [23]:
correct_products = numbers * make_array(1577, 1577, 1577, 1577)
correct_products

array([      66234,     6661248, 66900162648,     -394250])

In [24]:
grader.check("q3_3")

q3_3 results: All test cases passed!

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](https://www.noaa.gov/), all the temperatures are in Fahrenheit.

Convert all the temperatures to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$, i.e. $C = (F - 32) * \frac{5}{9}$. After converting the temperatures to Celsius, make sure to **ROUND** the final result  to the nearest integer using the `np.round` function. 

<!--
BEGIN QUESTION
name: q3_4
-->

In [25]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = np.round((max_temperatures - 32) * 5/9, 0)
celsius_max_temperatures

array([ -4.,  31.,  32., ...,  17.,  23.,  16.])

In [26]:
grader.check("q3_4")

q3_4 results: All test cases passed!

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the daily temperature range for each day. That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units and give your answer in Celsius!** Make sure **NOT** to round your answer for this question!

*Note:* Remember that in Question 4, `celsius_max_temperatures` was rounded, so you might not want to use that variable in this question.

<!--
BEGIN QUESTION
name: q3_5
-->

In [27]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

def f_to_c(val): return (val - 32) * 5/9

celsius_temperature_ranges = f_to_c(max_temperatures) - f_to_c(min_temperatures)
celsius_temperature_ranges

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

In [28]:
grader.check("q3_5")

q3_5 results: All test cases passed!

## 4. Old Faithful


Remember that the tests from this point on will **not** necessarily tell you whether or not your answers are correct.

Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

<!--
BEGIN QUESTION
name: q4_1
-->

In [29]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

from statistics import mean 

shortest = min(waiting_times)
longest = max(waiting_times)
average = mean(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70 minutes on average.


In [30]:
grader.check("q4_1")

q4_1 results: All test cases passed!

**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes.

*Hint*: We want to return the absolute value of the biggest decrease.

*Note*: `np.diff()` calculates the difference between subsequent values in an array. For example, calling `np.diff()` on the array `make_array(1, 8, 3, 5)` evaluates to `array([8 - 1, 3 - 8, 5 - 3])`, or `array([7, -5, 2])`.

<!--
BEGIN QUESTION
name: q4_2
-->

In [31]:
biggest_decrease = abs(np.diff(waiting_times))
biggest_decrease

array([25, 20, 12, 23, 30, 33,  3, 34, 34, 31, 30,  6, 31, 36, 31, 10, 22,
       32, 27, 28,  4, 31,  9,  5,  9, 28, 21,  2,  1,  6,  4, 11, 14,  6,
       22,  4, 32, 21, 31, 10, 22, 26, 26, 15, 10, 19, 11, 29, 23, 16, 15,
       36, 26, 26, 29, 12,  7, 13,  4, 22, 25, 36, 34, 22, 32, 14,  0, 13,
        8,  9, 26, 23,  8,  9, 14, 16, 18,  2,  7,  8,  7, 12,  5,  8, 15,
       12,  4, 32, 38, 26, 30, 40, 28, 15,  9, 12,  9, 24, 31, 20, 26, 39,
       34,  2, 34, 37, 32, 34,  5,  6, 16, 30, 10, 20, 22, 31, 35, 26, 28,
       34, 16,  8, 21, 32,  7, 36, 37, 27, 35, 45, 38, 27, 33, 43, 36, 31,
       35, 33, 26,  2, 21, 22,  5,  1, 17, 21, 31, 47, 43, 24,  0, 12, 16,
       10,  1, 11, 12, 40, 36, 44, 41, 28, 20, 12, 10, 13, 25, 36, 41, 44,
        8, 20,  9, 13,  0,  8, 23, 35, 11, 19, 22,  6,  0, 32, 27,  6, 38,
       37, 28, 26, 24, 19,  8,  7,  4,  6, 10, 26, 27, 18, 22,  9, 38, 25,
       32, 31,  7, 35, 34, 12,  9, 31, 26, 11, 12, 23, 41, 39, 21, 26, 32,
       28, 21,  3,  1,  1

In [32]:
grader.check("q4_2")

q4_2 results:
    q4_2 - 1 result:
        Trying:
            biggest_decrease == 47
        Expecting:
            False
        **********************************************************************
        Line 4, in q4_2 0
        Failed example:
            biggest_decrease == 47
        Expected:
            False
        Got:
            array([False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False,  True, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False, False, False], dtype=bool)

    q4_2 - 2 result:
        Trying:
            30 <= biggest_decrease < 47
        Expecting:
            True
        **********************************************************************
        Line 3, in q4_2 1
        Failed example:
            30 <= biggest_decrease < 47
        Exception raised:
            Traceback (most recent call last):
              File "/opt/conda/lib/python3.7/doctest.py", line 1337, in __run
                compileflags, 1), test.globs)
              File "<doctest q4_2 1[0]>", line 1, in <module>
                30 <= biggest_decrease < 47
            ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Question 3.** The `faithful_with_eruption_nums` table contains two columns: `eruption_number`, which represents the number of that eruption, and `waiting`, which represents the time spent waiting after that eruption. For example, take the first two rows of the table:

| eruption number | waiting |
|-----------------|---------|
| 1               | 79      |
| 2               | 54      |

We can read this as follows: after the first eruption, we waited 79 minutes for the second eruption. Then, after the second eruption, we waited 54 minutes for the third eruption.

Suppose Oscar and Wendy started watching Old Faithful at the start of the first eruption. Assume that they watch until the end of the tenth eruption. For some of that time they will be watching eruptions, and for the rest of the time they will be waiting for Old Faithful to erupt. How many minutes will they spend waiting for eruptions? 

*Hint #1:* One way to approach this problem is to use the `take` or `where` method on the table `faithful_with_eruption_nums`. 

*Hint #2:* `first_nine_waiting_times` must be an array.

<!--
BEGIN QUESTION
name: q4_3
-->

In [33]:
# The following two lines load in our faithful_with_eruption_nums table
faithful = Table.read_table('old_faithful.csv').drop("eruptions")
faithful_with_eruption_nums = faithful.with_column("eruption number", np.arange(faithful.num_rows) + 1).select(1, 0)

first_nine_waiting_times = faithful_with_eruption_nums.where('eruption number', are.below(10)).column('waiting')
total_waiting_time_until_tenth = np.cumsum(first_nine_waiting_times)[-1]
total_waiting_time_until_tenth

633

In [34]:
grader.check("q4_3")

q4_3 results: All test cases passed!

**Question 4.** Let’s imagine your guess for the next waiting time was always just the length of the previous waiting time. If you always guessed the previous waiting time, how big would your error in guessing the waiting times be, on average?

For example, since the first four waiting times are 79, 54, 74, and 62, the average difference between your guess and the actual time for just the second, third, and fourth eruptions would be $\frac{|79-54|+ |54-74|+ |74-62|}{3} = 19$.

<!--
BEGIN QUESTION
name: q4_4
-->

In [35]:
wait_times = faithful.column('waiting')

average_error = np.sum(np.abs(np.diff(wait_times))) / (len(wait_times) - 1)
average_error

20.520295202952031

In [36]:
grader.check("q4_4")

q4_4 results: All test cases passed!

## 5. Tables


**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: `fruit name` and `count`.  Assign the new table to the variable `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

<!--
BEGIN QUESTION
name: q5_1
-->

In [37]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns(
        'fruit name', ['apple', 'orange', 'pineapple'],
        'count', [4, 3, 3])
fruits

fruit name | count
apple      | 4
orange     | 3
pineapple  | 3

In [38]:
grader.check("q5_1")

q5_1 results: All test cases passed!

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit. Load it as a table named `inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table.

<!--
BEGIN QUESTION
name: q5_2
-->

In [39]:
inventory = Table.read_table('inventory.csv')
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [40]:
grader.check("q5_2")

q5_2 results: All test cases passed!

**Question 3.** Does each box at the fruit stand contain a different fruit? Set `all_different` to `True` if each box contains a different fruit or to `False` if multiple boxes contain the same fruit.

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.

<!--
BEGIN QUESTION
name: q5_3
-->

In [41]:
all_different = True
all_different

True

In [42]:
grader.check("q5_3")

q5_3 results: All test cases passed!

**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`.

<!--
BEGIN QUESTION
name: q5_4
-->

In [43]:
sales = Table.read_table('sales.csv')
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [44]:
grader.check("q5_4")

q5_4 results: All test cases passed!

**Question 5.** How many fruits did the store sell in total on that day?

<!--
BEGIN QUESTION
name: q5_5
-->

In [45]:
total_fruits_sold = sum(sales.column('count sold'))
total_fruits_sold

638

In [46]:
grader.check("q5_5")

q5_5 results: All test cases passed!

**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

<!--
BEGIN QUESTION
name: q5_6
-->

In [47]:
calc = lambda x, y: x * y
total_revenue = sum(calc(sales.column('count sold'), sales.column('price per fruit ($)')))
total_revenue

106.84999999999999

In [48]:
grader.check("q5_6")

q5_6 results: All test cases passed!

**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

<!--
BEGIN QUESTION
name: q5_7
-->

In [49]:
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [50]:
remaining_inventory = Table().with_columns(
        'box ID', inventory.column('box ID'),
        'fruit name', inventory.column('fruit name'),
        'count', inventory.column('count') - sales.column('count sold'))

remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23

In [51]:
grader.check("q5_7")

q5_7 results: All test cases passed!

## Congratulations! You're done with Homework 2!

Be sure to run all of the cells and the grader checks and verify that they all pass, then choose **Download as PDF via LaTeX** from the **File** menu, as well as **Download as Notebook** from the **File** menu, correctly name your files, and submit the two files on **canvas**.